name: Docker Preview Image CI

on:
  pull_request:
    branches:
      - "preview/**"

jobs:
  build-and-push-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Generate Incremental Preview Tag
        id: tag
        run: echo "TAG=preview/$(date +%s)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/hathon-tokenbridge:${{ env.TAG }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/hathon-tokenbridge:${{ env.TAG }} ${{ secrets.DOCKER_HUB_USERNAME }}/hathon-tokenbridge:preview-latest

      - name: Push Docker image with preview tag
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hathon-tokenbridge:${{ env.TAG }}

      - name: Push Docker image with "preview-latest" tag
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hathon-tokenbridge:preview-latest
